### ISSUE TITLE
The table.vue nether dialog out of the question

### ISSUE THREAD

**Issue by ghost** [reg21st/vue2-management-platform#10]
This table component editing function does not pop up dialog.I think you wrote down an instruction.

:visible="dialogFormVisible"

**Comment by suweiteng** [comment]
@zoudongyang 
谢谢指正。
我定位了下问题，系elementUI版本升级导致。
在1.x版本时，写 v-model="dialogFormVisible" 就可以实现。
在2.x版本时，上述代码已失效，需用visible。
可在线查看新老版本的代码示例：   https://jsfiddle.net/cehy2cuz/
新版本切换为<script src="//unpkg.com/element-ui@2.3.2/lib/index.js"></script>

过几天更新本项目代码。

**Comment by suweiteng** [comment]
@zoudongyang 
已更新~欢迎体验
