### ISSUE TITLE
后台配置项返回格式出错，上传功能将不能正常使用！

### ISSUE THREAD

**Issue by zhanghaifeng213** [reg21st/vue2-management-platform#13]
![ejx sapn6q6 47cbnfz x](https://user-images.githubusercontent.com/26516275/41018666-819114d4-698d-11e8-9f5d-0bd51eb1e49b.png)
请问这个是怎么回事呢？在哪能改呢？

**Comment by suweiteng** [comment]
@zhanghaifeng213   
可以自行查阅UEditor文档，比如http://fex.baidu.com/ueditor/#server-path
