### ISSUE TITLE
打包后fa出现加载不到的问题

### ISSUE THREAD

**Issue by felanny** [reg21st/vue2-management-platform#16]
查看了下是引用路径不对，本来应该是
/dist/static/fonts/fontawesome-webfont.af7ae50.woff2
但是实际上是
/dist/static/css/static/fonts/fontawesome-webfont.af7ae50.woff2,
也就是说多出来一个/static/fonts,请问应该如何解决？

**Comment by felanny** [comment]
当然在css目录下手动放入/static/fonts/字体文件
也是可以解决的，但是从代码和配置角度来说怎么解决呢？

**Comment by suweiteng** [comment]
对webpack不熟悉的话，font字体可以在index.html里直接引入，字体文件一般不会变动。

`<link rel="stylesheet" href="./static/fonts/iconfont.css">`
