### ISSUE TITLE
打包后fa出现加载不到ueditor.config.js

### ISSUE THREAD

**Issue by 35860368** [reg21st/vue2-management-platform#17]
在config.js里添加build的assetsPublicPath的上下地址，线上打包提升找不到ueditor.config.js相关js文件，其原因是我的上下文路径是admin/static/ 但是打包后的js地址为static，缺少自定义的上下文路径名，请问怎么解决

**Comment by suweiteng** [comment]
路径问题主要有2方面影响。
一个是static/UE/ueditor.config.js中的window.UEDITOR_HOME_URL
一个是config/index.js中的assetsPublicPath
你这个情况应该是修改window.UEDITOR_HOME_URL，例如修改为admin/static/
