### ISSUE TITLE
关于路由的配置

### ISSUE THREAD

**Issue by DancingC** [reg21st/vue2-management-platform#18]
您好，请问在您的这个项目中，点击table菜单，然后点击表格中的编辑按钮，不显示弹出框，而是在当前table页面中加载编辑页，请问这个功能怎么实现呢？我配置了路由没找到完美的实现方法，我的路由菜单结构，跟您项目中的结构是一样的，希望能给点意见

**Comment by suweiteng** [comment]
您是想在点击编辑按钮后，加载一个新的编辑页面是吧，那应该配置路由然后跳转就可以啊。
或者无需路由，直接隐藏一个编辑页的组件也可以（相当于编辑器弹窗放大，放大到整个页面）
请详细说明下，为何配置路由后没有完美实现方式呢？
