### ISSUE TITLE
ueditor打包

### ISSUE THREAD

**Issue by yangM00A** [reg21st/vue2-management-platform#2]
你好，我照着你的项目，在自己的项目中，将ueditor,创建问全局组件，但是现在我打包的时候，ueditor依赖的css都打包不上，我看见你的项目dist中直接将ueditor依赖的自己放在了static中。难道是打包后，直接将ueditor依赖的资源放在打包后的dist中？？有没有一起打包的方法？

**Comment by suweiteng** [comment]
@kingyangmeng 
你好，static中的资源是不参与打包的，是有意为之。这些资源不参与打包是有意为之。因为，不打包的情况下，这些资源才方便挂CDN，方便被多页面应用引用，方便缓存；
如果想让参与这些资源参与打包，可以换一下引用方式 或者 搜索下npm版本的ueditor。
