### ISSUE TITLE
想问一下static下面的资源是如何访问的。

### ISSUE THREAD

**Issue by swit1983** [reg21st/vue2-management-platform#3]
ueditor 放在static下面，但是只要是import进去的，webpack都会打包进去吧.  打包的时候把static放到dist下面主要是为了访问ueditor的图片吗？但我这边打包跑起来会报错，uParse is not defined。
3Q

**Comment by suweiteng** [comment]
可以参考：http://www.cnblogs.com/dmcl/p/7152711.html

**Comment by suweiteng** [comment]
@swit1983   
可以参考这种http://www.cnblogs.com/dmcl/p/7152711.html
评论里你这种疑问。

**Comment by suweiteng** [comment]
@swit1983 
是的，打包会引入。ueditor里不少内容，具体哪些被打包了没有细致了解过，所以直接放到这里了。
uParse is not defined的问题，可以参考这种http://www.cnblogs.com/dmcl/p/7152711.html
评论里你这种疑问。
