### ISSUE TITLE
百度的富文本编辑器报错 不知为何 

### ISSUE THREAD

**Issue by w19871029** [reg21st/vue2-management-platform#5]
Uncaught ReferenceError: uParse is not defined

**Comment by suweiteng** [comment]
请参考博客中评论有类似问题 ：http://www.cnblogs.com/dmcl/p/7152711.html @w19871029

**Comment by w19871029** [comment]
已经看到 使用的你的文件 也是不行 还是会报 uParse is not defined

**Comment by suweiteng** [comment]
@w19871029     严格模式吗  贴点截图吧

**Comment by w19871029** [comment]
嗯 好啦 我把文件放到static里面 就可以啦 今天发现了一个问题 就是必须放到static里面 放到其他文件夹下就会报错
![image](https://user-images.githubusercontent.com/5523615/34398925-b46145e4-ebbd-11e7-88a3-a3731327978e.png)
![image](https://user-images.githubusercontent.com/5523615/34398932-cb4b8b66-ebbd-11e7-8dfb-23aa6dec9859.png)
![image](https://user-images.githubusercontent.com/5523615/34398974-35d6e566-ebbe-11e7-9097-09cce8ce15ee.png)

特别奇怪 换成static这个文件夹路径就可以 感觉百度编辑器 不会写这么死把
